url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

#Navigation bar items from the header include file
navigation:
    - text: Services
    - text: Portfolio
    - text: About
    - text: Team
    - text: Contact
    
#Content from the services include file
services:
    - heading: E-Commerce
      icon: shopping-cart
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    - heading: Responsive Design
      icon: laptop
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    - heading: Web Security
      icon: lock
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.

#Content from the about include file
timeLine: 
    - path: 1.jpg
      dateRange: 2009-2011
      subHeading: Our Humble Beginnings
      description: This is a test!
    - inverted: timeline-inverted
      path: 2.jpg
      dateRange: March 2015
      subHeading: Test1
      description: This is a test!
    - path: 3.jpg
      dateRange: 2003-2020
      subHeading: Test2
      description: This is a test!
    - inverted: timeline-inverted
      path: 4.jpg
      dateRange: 2010-2012
      subHeading: Test3
      description: This is a test!
      
#Images from the clients include file
clientImages:
    - path: envato.jpg
    - path: designmodo.jpg
    - path: themeforest.jpg
    - path: creative-market.jpg

# Build settings
markdown: kramdown
permalink: pretty